services:
  postgres:
    image: postgres:alpine
    container_name: mattermost-postgres
    restart: always
    environment:
      - POSTGRES_USER=mattermost
      - POSTGRES_PASSWORD=mattermost
      - POSTGRES_DB=mattermost
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ~/.local/share/mattermost/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mattermost"]
      interval: 5s
      timeout: 5s
      retries: 5

  mattermost:
    image: mattermost/mattermost-team-edition:latest
    container_name: mattermost
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mattermost:mattermost@postgres/mattermost?sslmode=disable
      - MM_EMAILSETTINGS_SMTPSERVER=smtp.gmail.com
      - MM_EMAILSETTINGS_SMTPPORT=587
      - MM_EMAILSETTINGS_SMTPUSERNAME=minorugh@gmail.com
      - MM_EMAILSETTINGS_SMTPPASSWORD=lgtmybepfxbjbvsh
      - MM_EMAILSETTINGS_CONNECTIONSECURITY=STARTTLS
      - MM_EMAILSETTINGS_SENDEMAILFROM=minorugh@gmail.com
      - MM_EMAILSETTINGS_ENABLESMTPAUTH=true
    ports:
      - "8065:8065"
    volumes:
      - ~/docker-data/mattermost/data:/mattermost/data
      - ~/docker-data/mattermost/logs:/mattermost/logs
      - ~/docker-data/mattermost/config:/mattermost/config
      - ~/docker-data/mattermost/plugins:/mattermost/plugins
