;;; my-loaddefs.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from my-dired.el

(autoload 'my-documents "my-dired" "\
Open Documents dir." t)
(autoload 'backup-makefile "my-dired" "\
Open backup makefile." t)
(autoload 'my-abook "my-dired" "\
Open addressbook." t)
(autoload 'my-mutt "my-dired" "\
Open mutt dir." t)
(autoload 'my-zshrc "my-dired" "\
Open zshrc." t)
(autoload 'my-xsrv-dir "my-dired" "\
Open xsrv dir." t)
(autoload 'my-github-dir "my-dired" "\
Open github dir." t)
(autoload 'my-scr-dir "my-dired" "\
Open src dir." t)
(autoload 'my-minorugh-dir "my-dired" "\
Open minorugh.com dir." t)
(autoload 'my-github-local "my-dired" "\
Open github local dir." t)
(autoload 'my-junk-dir "my-dired" "\
Open junk file dir." t)
(autoload 'my-dropbox "my-dired" "\
Open Dropbox dir." t)
(autoload 'my-gh-dir "my-dired" "\
Open GH dir." t)
(autoload 'my-pages-dir "my-dired" "\
Open github pages dir." t)
(autoload 'my-org-dir "my-dired" "\
Open org dir." t)
(autoload 'my-docker-compose "my-dired" "\
Open docker-compose dir." t)
(autoload 'my-open-capture "my-dired" "\
Open `org-capture' file." t)
(autoload 'my-diary "my-dired" "\
Open diary file." t)
(autoload 'my-marquee-edit "my-dired" "\
Open marquee file." t)
(autoload 'my-kendai-edit "my-dired" "\
Open kendai file." t)
(autoload 'my-d_kukai "my-dired" "\
Open d_select file." t)
(autoload 'my-w_kukai "my-dired" "\
Open w_select file." t)
(autoload 'my-m_kukai "my-dired" "\
Open m_select file." t)
(autoload 'my-swan "my-dired" "\
Open s_select file." t)
(autoload 'my-mj_kukai "my-dired" "\
Open mj_select file." t)
(autoload 'my-tselext "my-dired" "\
Open tselext file." t)
(autoload 'my-dselext "my-dired" "\
Open d_selext file." t)
(autoload 'my-teirei "my-dired" "\
Open teirei file." t)
(autoload 'my-kinnei "my-dired" "\
Open kinnei file." t)
(autoload 'my-kinnei-draft "my-dired" "\
Open kinnei draft file." t)
(autoload 'my-year "my-dired" "\
Open year file." t)
(autoload 'my-year-draft "my-dired" "\
Open year draft file." t)
(autoload 'my-tpdia "my-dired" "\
Open tpdia file." t)
(autoload 'my-apvoice "my-dired" "\
Open apvoice file." t)


;;; Generated autoloads from my-git-show-file.el

(autoload 'my-git-show-file "my-git-show-file" "\
過去のコミットからファイルを取り出して ~/Dropbox/backup/tmp/ に保存する." t)


;;; Generated autoloads from my-github.el

(autoload 'github-deploy "my-github" "\
Insert current changelog buffer into CHANGELOG.md and open it." t)


;;; Generated autoloads from my-markdown.el

(autoload 'my-howm-fix-code-comments "my-markdown" "\
In code blocks, replace '# ' with '## '.
If region is active, process region only (anywhere in buffer).
Otherwise process whole file via Perl." t)
(autoload 'gen-toc-term "my-markdown" "\
Run gen_toc.pl for current Markdown file in gnome-terminal." t)


;;; Generated autoloads from my-template.el

(autoload 'my-diary-new-post "my-template" "\
Open diary file and insert template." t)
(autoload 'my-tpdia-new-post "my-template" "\
Open tpdia file and insert template." t)
(autoload 'my-minoru_sen "my-template" "\
Insert kukai header template." t)
(autoload 'my-teirei-new-post "my-template" "\
Open teirei file and insert template." t)
(autoload 'my-swan-new-post "my-template" "\
Open swan file and insert template." t)
(autoload 'my-m_kukai-new-post "my-template" "\
Open m_kukai file and insert template." t)
(autoload 'my-ap-new-post "my-template" "\
Insert ap template at current position." t)
(autoload 'my-apvoice-new-post "my-template" "\
Open apvoice file and insert template." t)
(autoload 'my-tselext-new-post "my-template" "\
Open tselext file and insert template." t)
(autoload 'my-dselext-new-post "my-template" "\
Open d_selext file and insert template." t)
(autoload 'my-year-new-post "my-template" "\
Insert year entry template at current position." t)
(autoload 'my-haiku-note "my-template" "\
Open haiku note file." t)
(autoload 'my-haiku-note-post "my-template" "\
Open haiku note file and insert template." t)

;;; End of scraped data

(provide 'my-loaddefs)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; my-loaddefs.el ends here
